apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lg-agent.fullname" . }}-api-secret
  labels:
    app: {{ include "lg-agent.name" . }}-api
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.api.env.DATABASE_URL | quote }}
