export const SANDBOX_EXECUTOR = Symbol('SANDBOX_EXECUTOR');
export const EXECUTION_WORKSPACE_ROOT = Symbol('EXECUTION_WORKSPACE_ROOT');
export const SANDBOX_EXECUTION_TIMEOUT_MS = Symbol('SANDBOX_EXECUTION_TIMEOUT_MS');
